// Categorías de negocio con keywords para filtrar licitaciones relevantes
export const RUBROS = [
  {
    id: 'mantenimiento',
    label: 'Mantenimiento Industrial',
    emoji: '⚙️',
    description: 'Mantenimiento de equipos, plantas industriales, maquinaria y sistemas',
    color: 'bg-zinc-50 border-zinc-200 text-zinc-700',
    colorActive: 'bg-zinc-700 text-white border-zinc-700',
    keywords: ['mantenimiento industrial', 'mantención industrial', 'mantencion industrial',
      'mantención equipos', 'mantencion equipos', 'mantenimiento preventivo',
      'mantenimiento correctivo', 'servicio técnico industrial', 'reparación maquinaria',
      'reparacion maquinaria', 'overhaul', 'lubricación', 'lubricacion',
      'mantenimiento planta', 'mantención planta', 'sistema industrial',
      'automatización', 'automatizacion', 'instrumentación', 'instrumentacion'],
  },
  {
    id: 'obras',
    label: 'Obras y Construcción',
    emoji: '🏗️',
    description: 'Obras menores, mantención de infraestructura, reparaciones civiles',
    color: 'bg-orange-50 border-orange-200 text-orange-700',
    colorActive: 'bg-orange-500 text-white border-orange-500',
    keywords: ['obra menor', 'obras menores', 'mantención', 'mantencion', 'reparación',
      'reparacion', 'infraestructura', 'techado', 'cubierta', 'piso',
      'revestimiento', 'tabique', 'ventana', 'puerta', 'instalación', 'instalacion',
      'sanitaria', 'pintura exterior', 'carpintería', 'carpinteria', 'construcción',
      'construccion', 'edificación', 'edificacion', 'pavimento', 'excavación'],
  },
  {
    id: 'electricidad',
    label: 'Electricidad e Iluminación',
    emoji: '⚡',
    description: 'Instalaciones eléctricas, iluminación, tableros, energía',
    color: 'bg-yellow-50 border-yellow-200 text-yellow-700',
    colorActive: 'bg-yellow-500 text-white border-yellow-500',
    keywords: ['eléctrico', 'electrico', 'eléctrica', 'electrica', 'instalación eléctrica',
      'instalacion electrica', 'iluminación', 'iluminacion', 'luminaria', 'tablero',
      'transformador', 'generador', 'cable eléctrico', 'conductor', 'interruptor',
      'tomacorriente', 'energía', 'energia', 'potencia', 'UPS', 'baterías', 'baterias',
      'fotovoltaico', 'solar', 'alumbrado público', 'alumbrado publico'],
  },
  {
    id: 'mecanica',
    label: 'Mecánica y Equipos',
    emoji: '🔩',
    description: 'Equipos industriales, maquinaria pesada, motores, bombas',
    color: 'bg-stone-50 border-stone-200 text-stone-700',
    colorActive: 'bg-stone-600 text-white border-stone-600',
    keywords: ['mecánica', 'mecanica', 'maquinaria', 'equipo industrial', 'motor',
      'bomba', 'compresor', 'válvula', 'valvula', 'rodamiento', 'correa',
      'transmisión', 'transmision', 'reductor', 'engranaje', 'soldadura',
      'torno', 'fresadora', 'grúa', 'grua', 'montacargas', 'vehículo pesado',
      'vehiculo pesado', 'camión', 'camion', 'retroexcavadora', 'equipos pesados'],
  },
  {
    id: 'seguridad',
    label: 'Seguridad y Vigilancia',
    emoji: '🔒',
    description: 'Guardias, CCTV, control de acceso, alarmas, seguridad industrial',
    color: 'bg-indigo-50 border-indigo-200 text-indigo-700',
    colorActive: 'bg-indigo-600 text-white border-indigo-600',
    keywords: ['seguridad', 'vigilancia', 'guardia', 'CCTV', 'cámara', 'camara',
      'control acceso', 'alarma', 'monitoreo', 'ronda', 'portería', 'porteria',
      'seguridad privada', 'custodia', 'seguridad industrial', 'seguridad operacional',
      'prevención riesgos', 'prevencion riesgos', 'detector', 'incendio', 'extintor'],
  },
  {
    id: 'ferreteria',
    label: 'Ferretería y Materiales',
    emoji: '🔧',
    description: 'Materiales de construcción, herramientas, plomería, gasfitería',
    color: 'bg-amber-50 border-amber-200 text-amber-700',
    colorActive: 'bg-amber-500 text-white border-amber-500',
    keywords: ['ferretería', 'ferreteria', 'materiales construcción', 'materiales construccion',
      'pinturas', 'herramientas', 'plomería', 'plomeria', 'tornillos',
      'adhesivos', 'clavos', 'tuberías', 'tuberia', 'cables', 'fittings', 'gasfitería',
      'gasfiteria', 'silicona', 'sellador', 'lija', 'cemento', 'áridos', 'aridos'],
  },
  {
    id: 'transporte',
    label: 'Transporte y Logística',
    emoji: '🚛',
    description: 'Fletes, traslados, arriendo de vehículos, logística',
    color: 'bg-sky-50 border-sky-200 text-sky-700',
    colorActive: 'bg-sky-600 text-white border-sky-600',
    keywords: ['transporte', 'traslado', 'flete', 'logística', 'logistica',
      'arriendo vehículo', 'arriendo vehiculo', 'bus', 'minibús', 'minibus',
      'camioneta', 'distribución', 'distribucion', 'courier', 'despacho',
      'carga', 'bodega', 'almacenamiento', 'mudanza', 'retiro residuos'],
  },
  {
    id: 'tics',
    label: 'TI y Tecnología',
    emoji: '💻',
    description: 'Computadores, software, telecomunicaciones, servicios TI',
    color: 'bg-blue-50 border-blue-200 text-blue-700',
    colorActive: 'bg-blue-500 text-white border-blue-500',
    keywords: ['computador', 'laptop', 'notebook', 'tablet', 'software', 'licencia',
      'telecomunicaciones', 'servicio TI', 'servicio ti', 'infraestructura tecnológica',
      'infraestructura tecnologica', 'servidor', 'red', 'switch', 'router', 'firewall',
      'ciberseguridad', 'desarrollo software', 'aplicación', 'aplicacion', 'sistemas',
      'soporte técnico', 'soporte tecnico', 'monitor', 'impresora', 'tóner', 'toner'],
  },
  {
    id: 'aseo',
    label: 'Aseo y Limpieza',
    emoji: '🧹',
    description: 'Servicios de aseo, productos de limpieza, desinfección',
    color: 'bg-cyan-50 border-cyan-200 text-cyan-700',
    colorActive: 'bg-cyan-500 text-white border-cyan-500',
    keywords: ['aseo', 'limpieza', 'desinfección', 'desinfeccion', 'sanitización',
      'sanitizacion', 'productos higiene', 'jabón', 'jabon', 'detergente', 'cloro',
      'escoba', 'trapeador', 'paño', 'pano', 'servicio aseo', 'higiene ambiental'],
  },
  {
    id: 'alimentacion',
    label: 'Alimentación',
    emoji: '🍽️',
    description: 'Catering, colaciones, alimentos, víveres',
    color: 'bg-green-50 border-green-200 text-green-700',
    colorActive: 'bg-green-500 text-white border-green-500',
    keywords: ['alimentación', 'alimentacion', 'colación', 'colacion', 'catering',
      'almuerzo', 'desayuno', 'cena', 'víveres', 'viveres', 'abarrotes', 'alimentos',
      'café', 'cafe', 'té', 'te', 'fruta', 'verdura', 'pan', 'lácteos', 'lacteos'],
  },
  {
    id: 'salud',
    label: 'Salud e Insumos',
    emoji: '🏥',
    description: 'Insumos médicos, medicamentos, equipos clínicos',
    color: 'bg-red-50 border-red-200 text-red-700',
    colorActive: 'bg-red-500 text-white border-red-500',
    keywords: ['insumo médico', 'insumo medico', 'medicamento', 'fármaco', 'farmaco',
      'clínico', 'clinico', 'hospital', 'laboratorio', 'diagnóstico', 'diagnostico',
      'jeringa', 'guante', 'mascarilla', 'equipo médico', 'equipo medico',
      'dental', 'odontológico', 'odontologico', 'quirúrgico', 'quirurgico'],
  },
  {
    id: 'vestuario',
    label: 'Vestuario y EPP',
    emoji: '👷',
    description: 'Ropa de trabajo, equipos de protección personal, uniformes',
    color: 'bg-purple-50 border-purple-200 text-purple-700',
    colorActive: 'bg-purple-500 text-white border-purple-500',
    keywords: ['vestuario', 'uniforme', 'ropa trabajo', 'EPP', 'protección personal',
      'proteccion personal', 'casco', 'guantes', 'chaleco', 'zapatos seguridad',
      'calzado seguridad', 'arnés', 'arnes', 'lentes seguridad', 'overol'],
  },
  {
    id: 'jardineria',
    label: 'Jardines y Áreas Verdes',
    emoji: '🌿',
    description: 'Mantención de jardines, podas, paisajismo, áreas verdes',
    color: 'bg-emerald-50 border-emerald-200 text-emerald-700',
    colorActive: 'bg-emerald-600 text-white border-emerald-600',
    keywords: ['jardín', 'jardin', 'jardines', 'área verde', 'area verde', 'áreas verdes',
      'areas verdes', 'poda', 'corte pasto', 'grass', 'pasto', 'riego',
      'paisajismo', 'vivero', 'planta', 'árbol', 'arbol', 'forestación',
      'forestacion', 'mantención jardín', 'mantencion jardin'],
  },
  {
    id: 'servicios',
    label: 'Servicios Profesionales',
    emoji: '📋',
    description: 'Consultoría, capacitación, asesoría, auditoría',
    color: 'bg-slate-50 border-slate-200 text-slate-700',
    colorActive: 'bg-slate-600 text-white border-slate-600',
    keywords: ['consultoría', 'consultoria', 'capacitación', 'capacitacion', 'asesoría',
      'asesoria', 'auditoría', 'auditoria', 'estudio', 'levantamiento', 'diagnóstico',
      'diagnostico', 'evaluación', 'evaluacion', 'formación', 'formacion', 'taller',
      'charla', 'servicio profesional', 'arriendo', 'ingeniería', 'ingenieria',
      'proyecto', 'diseño', 'diseño arquitectónico', 'topografía', 'topografia'],
  },
]

export function filterByRubro(licitaciones, rubroId) {
  const rubro = RUBROS.find(r => r.id === rubroId)
  if (!rubro) return licitaciones
  return licitaciones.filter(l => {
    const nombre = (l.Nombre ?? '').toLowerCase()
    return rubro.keywords.some(kw => nombre.includes(kw.toLowerCase()))
  })
}
